### PR TITLE
fix: add cli

### LINKED ISSUE #43: automate the deploy process
right now i am deploying by hand to github pages

the magical incantation goes something like this: 

---

clean existing local `gh-pages`

`git branch -D gh-pages`

`npm run build`

remove `build` from `.gitignore`

checkout new branch, for example `deploy/my-deploy`

`git add .`

`git commit -av`

`git subtree split --prefix build -b gh-pages`

`git push -f origin gh-pages:gh-pages`

### LINKED ISSUE #45: support for uiSchema configuration (split view, auto expanding methods and params via toggles)
**Describe the feature you'd like**
I'd like to have a way to configure the expand or collapse state of the methods and their children.

**Current Problem**
they are closed now by default, but there is `state.uiSchema.params["ui:defaultExpanded"]` in `App.js` to configure this on and off.

image

**Solution You'd like to see**
I'd like to see it as both another `checkbox` toggle in the `AppBar` and via `uiSchema` object via querystring (theres an existing usage of `qs` already).
`?uiSchema=` 

image

### LINKED ISSUE #113: The automated release is failing 🚨
## :rotating_light: The automated release from the `master` branch failed. :rotating_light:

I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.

You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.

Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.

Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `master` branch. You can also manually restart the failed CI job that runs **semantic-release**.

If you are not sure how to resolve this, here is some links that can help you:
- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)
- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)
- [Support channels](https://github.com/semantic-release/semantic-release#get-help)

If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.

---

### No npm token specified.

An [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the `NPM_TOKEN` environment variable on your CI environment.

Please make sure to create an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the `NPM_TOKEN` environment variable on your CI environment. The token must allow to publish to the registry `https://registry.npmjs.org/`.

---

Good luck with your project ✨

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

### LINKED ISSUE #114: add CLI
**Describe the feature**
I'd like CLI interface to pass a schema to like:

```
npm install -g @open-rpc/playground
open-rpc-playground -s <schema>
// => Server listening on localhost:3000
```

### PR DESCRIPTION
**Pull request by shanejonas**
fixes #114
fixes #113
fixes #45
fixes #43

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -147,7 +170,7 @@ export default class App extends React.Component<{}, IState> {
           onSplitViewChange={this.handleUISchemaAppBarChange("ui:splitView")}
           onChangeUrl={this.handleUrlChange} />
         <div style={{ height: "100%", display: "flex", flexDirection: "row" }}>
-          { this.state.uiSchema.appBar["ui:splitView"] &&
+          {this.state.uiSchema.appBar["ui:splitView"] &&
```
Comment (BelfordZ) [inline src/App.tsx]: probably still want the `&`

File: src/AppBar/AppBar.tsx [hunk 2]
```diff
@@ -1,57 +1,87 @@
...
-              alt="open-rpc"
-              height="30"
-              width="30"
-              src={this.props.uiSchema && this.props.uiSchema.appBar["ui:logoUrl"]} />
-              <Grid item xs={2}>
-                <Typography variant="h6">{this.props.uiSchema && this.props.uiSchema.appBar["ui:title"]}</Typography>
+        <Toolbar>
+          <Grid justify="space-evenly" alignItems="center" container spacing={24}>
+            <Grid item xs={6} sm={3} direction="row" justify="flex-start" container>
+              {this.props.uiSchema && this.props.uiSchema.appBar && this.props.uiSchema.appBar["ui:logoUrl"] &&
```
Comment (BelfordZ) [inline src/AppBar/AppBar.tsx]: `&&` ?
